### ISSUE TITLE
As a master I want to create the list of inventory so event's participants can see needs equipment

### ISSUE THREAD

**Issue by Andriets** [EventsExpress-SoftServe/EventsExpress#140]

**Comment by Andriets** [comment]
- [x] Expand the DB and correspondive repo

- [x] Implement the logic of creating an inventory list

- [x] Create form on UI

**Comment by Andriets** [comment]
[Uploading sch_10_29_20.pdf…]()

**Comment by Andriets** [comment]
![photo_2020-10-30_16-45-11](https://user-images.githubusercontent.com/55383233/97719097-5d409c80-1acf-11eb-9672-512f047ff87c.jpg)
