### ISSUE TITLE
As an user I want to cancel my event

### ISSUE THREAD

**Issue by Avalon412** [EventsExpress-SoftServe/EventsExpress#93]

**Comment by mehalyna** [comment]
1. Check the possibility to modify the Events entity. Maybe it'll be more effective to modify the type of 'block/unblock' column. And change the corresponding property in the Event model.
2. You may use an enum to switch the status of the event.

**Comment by Avalon412** [comment]
- [x] Create EventStatusHistory model in database project and corresponding repo. Use enum for event status representing.

- [x] Implement logic of changing event status

- [ ] Create "Cancel" button on the event form and connect it`s logic with backend
